dv_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('', include('django.contrib.auth.urls')), 
    
    path('admin/', admin.site.urls),
]

myapp/urls.py
from django.urls import path, re_path
from . import views





urlpatterns = [
    

    path('loginpage', views.loginPage, name='login_user'),
    path('logout', views.logoutUser, name='logout'),
    path('register_user', views.register_user, name='register_user'),

    path('userhomepage', views.userHomepage, name='user-homepage'),
    path('form_view_error', views.form_view_error, name='form_view_error'),

    path('', views.welcome, name='welcome'),

    path('step1_page', views.form_one_page, name='step1_page'),
    path('step1', views.Step1_Form_Completion, name='step1'),
    path('form_view', views.Step1_Form_View, name='form_view'),
    path('edit/<step_one>', views.editpost, name='editpost'),
    path('delete/<step_one>', views.Step1_Form_Delete, name='delete-post'),

    path('step2_page', views.form_two_page, name='step2_page'),
    path('step2', views.Step2_Form_Completion, name='step2'),
    path('form_view2', views.Step2_Form_View, name='form_view2'),
    path('edit2/<step_two>', views.editpost2, name='editpost2'),
    path('delete2/<step_two>', views.Step2_Form_Delete, name='delete-post2'),

    path('step3_page', views.form_three_page, name='step3_page'),
    path('step3', views.Step3_Form_Completion, name='step3'),
    path('form_view3', views.Step3_Form_View, name='form_view3'),
    path('edit3/<step_three>', views.editpost3, name='editpost3'),
    path('delete3/<step_three>', views.Step3_Form_Delete, name='delete-post3'),

    path('step4_page', views.form_four_page, name='step4_page'),
    path('step4', views.Step4_Form_Completion, name='step4'),
    path('form_view4', views.Step4_Form_View, name='form_view4'),
    path('edit4/<step_four>', views.editpost4, name='editpost4'),
    path('delete4/<step_four>', views.Step4_Form_Delete, name='delete-post4'),

    path('step5_page', views.form_five_page, name='step5_page'),
    path('step5', views.Step5_Form_Completion, name='step5'),
    path('form_view5', views.Step5_Form_View, name='form_view5'),
    path('edit5/<step_five>', views.editpost5, name='editpost5'),
    path('delete5/<step_five>', views.Step5_Form_Delete, name='delete-post5'),

    path('step6_page', views.form_six_page, name='step6_page'),
    path('step6', views.Step6_Form_Completion, name='step6'),
    path('form_view6', views.Step6_Form_View, name='form_view6'),
    path('edit6/<step_six>', views.editpost6, name='editpost6'),
    path('delete6/<step_six>', views.Step6_Form_Delete, name='delete-post6'),

    path('step7_page', views.form_seven_page, name='step7_page'),
    path('step7', views.Step7_Form_Completion, name='step7'),
    path('form_view7', views.Step7_Form_View, name='form_view7'),
    path('edit7/<step_seven>', views.editpost7, name='editpost7'),
    path('delete7/<step_seven>', views.Step7_Form_Delete, name='delete-post7'),

    path('step8_page', views.form_eight_page, name='step8_page'),
    path('step8', views.Step8_Form_Completion, name='step8'),
    path('form_view8', views.Step8_Form_View, name='form_view8'),
    path('edit8/<step_eight>', views.editpost8, name='editpost8'),
    path('delete8/<step_eight>', views.Step8_Form_Delete, name='delete-post8'),


    path('base', views.base, name='base'),
    path('shell_test', views.shellTesting, name='shell_test'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm



class StepOne(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	update = "Update"
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.update

class StepTwo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	update = "Update"
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	box7 = models.CharField(max_length=100, null=True)
	box8 = models.CharField(max_length=100, null=True)
	box9 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.update

class StepThree(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	update = "Update"
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	box7 = models.CharField(max_length=100, null=True)
	box8 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.update


class StepFour(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	update = "Update"
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	box7 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.update


class StepFive(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	update = "Update"
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.update

class StepSix(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	name ='Form 6 Name'
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	
	def __str__(self):
		return self.name

class StepSeven(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	name ='Form 7 Name'
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	box7 = models.CharField(max_length=100, null=True)

	
	def __str__(self):
		return self.name

class StepEight(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	name ='Form 8 Name'
	box1 = models.CharField(max_length=100, null=True)
	box2 = models.CharField(max_length=100, null=True)
	box3 = models.CharField(max_length=100, null=True)
	box4 = models.CharField(max_length=100, null=True)
	box5 = models.CharField(max_length=100, null=True)
	box6 = models.CharField(max_length=100, null=True)
	box7 = models.CharField(max_length=100, null=True)
	
	
	def __str__(self):
		return self.name



# class CreateUserForm(UserCreationForm):
# 	class Meta:
# 		model = User
# 		fields = ['username', 'password1', 'password2']

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt





###General###

def base(request):
	"""css, navbar and block content to include on every page"""
	return render(request, 'base.html')

def userHomepage(request):
	"""Gets objects to display on user homepage and redirects user to user homepage"""
	return render(request, 'index.html')

def form_view_error(request):
	""" Display redirect when no form has been completed"""
	return render(request, 'redirect_userhome.html')

def form_one_page(request):
	form1 = StepOne.objects.filter(user=request.user)
	step1 = StepOne.objects.filter(user=request.user) # if you want to mess with messages.
	#form1 = StepOne.objects.all() # this would get the last form submitted by any user being passed.
	context = { 'form1': form1,
				'step1': step1
	}
	"""Takes User to Step1 Page"""
	return render(request, 'form_one_page.html', context)

def form_two_page(request):
	"""Takes User to Step2 Page"""
	form2 = StepTwo.objects.filter(user=request.user)
	context = { 'form2': form2,
	}
	return render(request, 'form_two_page.html', context)

def form_three_page(request):
	"""Takes User to Step3 Page"""
	form3 = StepThree.objects.filter(user=request.user)
	context = { 'form3': form3,
	}
	return render(request, 'form_three_page.html', context)

def form_four_page(request):
	"""Takes User to Step4 Page"""
	form4 = StepFour.objects.filter(user=request.user)
	context = { 'form4': form4,
	}
	return render(request, 'form_four_page.html', context)

def form_five_page(request):
	"""Takes User to Step5 Page"""
	form5 = StepFive.objects.filter(user=request.user)
	context = { 'form5': form5,
	}
	return render(request, 'form_five_page.html', context)

def form_six_page(request):
	"""Takes User to Step6 Page"""
	form6 = StepSix.objects.filter(user=request.user)
	context = { 'form6': form6,
	}
	return render(request, 'form_six_page.html', context)

def form_seven_page(request):
	"""Takes User to Step7 Page"""
	form7 = StepSeven.objects.filter(user=request.user)
	context = { 'form7': form7,
	}
	return render(request, 'form_seven_page.html', context)

def form_eight_page(request):
	"""Takes User to Step8 Page"""
	form8 = StepEight.objects.filter(user=request.user)
	context = { 'form8': form8,
	}
	return render(request, 'form_eight_page.html', context)


###########Users##############

def register_user(request):
	form = UserCreationForm()
	if request.method == 'POST': #if someone has filled out a form do something.
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			password2 = form.cleaned_data['password2']
			user = authenticate(username=username, password=password) #authenticate user
			login(request, user)  #log user in
			messages.success(request, 'Registration Successful')
			return redirect('user-homepage')
		else:
			messages.success(request, 'Already Registered, please log in.')
	return render(request, 'register.html', {'form': form} )


def shellTesting(request):
	thing = StepOne.objects.get(user=request.user)
	return render(request, 'shell_test.html', {'thing': thing})


def welcome(request):
	return render(request, 'welcome.html')


def loginPage(request):
	if request.method == "POST": #The user entered the info and logged in.
		username = request.POST.get('username') #this is sent from the front end through the login.html.
		password = request.POST.get('password')
		try:
			user= User.objects.get(username=username)
		except:
			messages.error(request, "User does not exist.")
		user = authenticate(request, username=username, password=password) #if get was successful authenticate user.
		if user is not None: #if we got a user
			login(request, user) #will add the session in the database and browser.
			return redirect('user-homepage')
		else:
			messages.error(request, "Username or password does not exist.")
	context = {}
	return render(request, 'login_registration.html', context)


def logoutUser(request):
	logout(request) # deletes the token/user session
	return redirect('welcome')

###########Form1##############

@login_required(login_url='login_user')
def Step1_Form_Completion(request):
	"""Generates link for user to fill out form"""
	form = StepOneForm                #Assign the form to the variable in the function.
	if request.method == 'POST':     # if method or form is requested then POST or send data to this function. If someone is loggded in . . 
		try:
			form = StepOneForm(request.POST) #the method is form and it is to be posted.
			if form.is_valid():             #if the form is django's definiton for 'valid' then save it and redirect the user home.
				form.instance.user = request.user
				form.save()
				return redirect('user-homepage')
		except:
			messages.success(request, 'Cannot resubmit. Please use "edit" instead.')
			return redirect('user-homepage')

	return render(request, 'form.html', {'form':form} ) # return  this function to the form.html page and let it use form as s variable and call it's attributes (form.box1)


@login_required(login_url='login_user')  #sends user back to login page if they try to go to a view form.
def Step1_Form_View(request):
	"""View for user to see completed form"""
	step1 = StepOne.objects.filter(user=request.user) #user can only view there form. request user and filter the objects/forms for there step oneform.
	return render(request,'form_view.html',{'step1': step1})

@login_required
def editpost(request, step_one ):
	"""Form1 Edit post function"""
	step1 = StepOne.objects.filter(user=request.user.id) #checks if there is a form. See html.
	step_one = StepOne.objects.get(pk=step_one) #Gets passed the form id by logged in user. See function form_one_page to see how it's passing query string.
	form = StepOneForm(instance=step_one)
	if request.method == 'POST':
		form = StepOneForm(request.POST, instance=step_one)
		if form.is_valid():
			form.save()
			return redirect('user-homepage')
	return render(request,'update_form.html', {"form": form, "step1": step1})

@login_required(login_url='login_user')
def Step1_Form_Delete(request, step_one): # WORKS! Just not the error messagse because there is no stepone.
	step1 = StepOne.objects.filter(user=request.user.id)  # this doesn't work. kept here as a note.
	form = StepOne.objects.get(pk=step_one)
	if request.method == "POST":
		form.delete()
		return redirect("user-homepage")
	context = {'form': form, "step1": step1}
	return render(request, 'delete_form1.html', context)

###########Form2##############

@login_required(login_url='login_user')
def Step2_Form_Completion(request):
	"""Generates link for user to fill out form"""
	form = StepTwoForm                
	if request.method == 'POST': 
		try:
			form = StepTwoForm(request.POST) 
			if form.is_valid():         
				form.instance.user = request.user
				form.save()
				return redirect('user-homepage')
		except:
			messages.success(request, 'Cannot resubmit. Please use "edit" instead.')
			return redirect('user-homepage')
	return render(request, 'form2.html', {'form':form} )


@login_required(login_url='login_user')  
def Step2_Form_View(request):
	"""View for user to see completed form"""
	step2 = StepTwo.objects.filter(user=request.user)
	return render(request, 'form_view2.html', {"step2": step2} )


@login_required
def editpost2(request, step_two ):
	"""Form1 Edit post function"""
	step2 = StepTwo.objects.filter(user=request.user)
	step_two = StepTwo.objects.get(pk=step_two)
	form2 = StepTwoForm(instance=step_two)
	if request.method == 'POST':
		form2 = StepTwoForm(request.POST, instance=step_two)
		if form2.is_valid():
			form2.save()
			return redirect('user-homepage')
	return render(request,'update_form2.html', {"form2": form2, "step2": step2})

@login_required(login_url='login_user')
def Step2_Form_Delete(request, step_two):
    form = StepTwo.objects.get(pk=step_two)
    if request.method == "POST":
    	form.delete()
    	return redirect("user-homepage")
    context = {'form': form}
    return render(request, 'delete_form2.html', context)


###########Form3##############


@login_required(login_url='login_user')
def Step3_Form_Completion(request):
	"""Generates link for user to fill out form"""
	form = StepThreeForm                
	if request.method == 'POST': 
		try:
			form = StepThreeForm(request.POST) 
			if form.is_valid():         
				form.instance.user = request.user
				form.save()
				return redirect('user-homepage')
		except:
			messages.success(request, 'Cannot resubmit. Please use "edit" instead.')
			return redirect('user-homepage')
	return render(request, 'form3.html', {'form':form} )


@login_required(login_url='login_user')  
def Step3_Form_View(request):
	"""View for user to see completed form"""
	step3 = StepThree.objects.filter(user=request.user)
	return render(request, 'form_view3.html', {"step3": step3} )

@login_required
def editpost3(request, step_three):
	"""Form3 Edit post function"""
	step3 = StepThree.objects.filter(user=request.user)
	step_three = StepThree.objects.get(pk=step_three) #Needs to be a form completed by any user for this to work.
	form3 = StepThreeForm(instance=step_three)
	if request.method == 'POST':
		form3 = StepThreeForm(request.POST, instance=step_three)
		if form3.is_valid():
			form3.save()
			return redirect('user-homepage')
	return render(request,'update_form3.html', {"form3": form3, "step3": step3})

@login_required(login_url='login_user')
def Step3_Form_Delete(request, step_three):
    form = StepThree.objects.get(pk=step_three)
    if request.method == "POST":

myapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">

    <!-- The line and href below are really important it formats the navbar and makes the "container" gutter work. -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>




  <body>
      {% include 'navbar.html' %}
      <br/>
    	<div class="container"> <!--creates a gutter for content on homepage, this is good.-->

	   {% block content %}

     {% endblock %}
      </div>
  </body>

</html>

myapp/templates/delete_form3.html
{% extends 'base.html' %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<p>Are you are you want to delete this form?</p>

			<form action="{% url 'delete-post3' form.id %}" method="POST" >

			{% csrf_token %}

			<a class= "btn btn-warning"  href="{% url 'user-homepage' %}" >Cancel</a>&emsp;

			<button type="submit" class="btn btn-danger" name="confirm">Delete</button>


			</form>
		</div>   
	</div>
</div>


{% endblock content %}

myapp/templates/form.html
{% extends 'base.html' %}

{% block content %}




<body>
    <div class="card card-body" >
		<form method='post' >

			{% csrf_token %}

  </label>

		<h3> Step 1: Safety during a violent incident. </h3>

		<p><p><b>I will not always be able to avoid violent incidents. In order to increase safety I may use a variety of strategies. I can use some of the following strategies: </b></p></p>
		<p>


		<b>A.</b> If I decide to leave, I will <textarea name="box1" id="id_box1"></textarea> (Practice how to get out safely. What doors, windows, elevators, stairwells, or fire escapes would you use?)
		<p>
		<b>B.</b> I can keep my purse and car keys ready and put them (location) <textarea name="box2" id="id_box2"></textarea> in order to leave quickly.
		</p>
		<p>
		<b>C.</b> I can tell <textarea name="box3" id="id_box3"></textarea> about the violence and request that she or he call the police if she or he hears suspicious noises coming from my house.
		</p>
		<p>
		<b>D.</b> I can teach my children how to use the telephone to contact the police, the fire department, and 911. E. I will use <textarea name="box4" id="id_box4"></textarea> as my code with my children or my
		friends so they can call for help.
		</p>
		<p>
		<b>F.</b> If I have to leave my home, I will go to <textarea name="box5" id="id_box5"></textarea>. (Decide this even if you don’t think there will be a next time.)
		<p>
		<b>G.</b> I can also teach some of these strategies to some or all of my children.
		</p>
		<p>
		<b>H.</b> When I expect we’re going to have an argument, I’ll try to move to a place that is low risk, such as <textarea name="box6" id="id_box6"></textarea>. (Try to avoid arguments in the bathroom, garage, kitchen, near weapons, or in rooms without access to an outside door.)
		</p>
		<p>
		<b>I.</b> I will use my judgment and intuition. If the situation is very serious, I can give my partner what he/she wants to calm him/her down.
		</p>

		<button class='submit_button' type="submit">Submit</button>
	</label>
		</form>
	</div>
  </textarea>

</body>


{% endblock content %}

myapp/templates/form_four_page.html
{% extends 'base.html' %}

<!--Row -->



{% block content %}

<h2>Safety with a Protection/Restraining Order</h2>

<table class="table table-striped table-hover table-bordered">

       <td><div class="span12" style="text-align:center">
          <a href="{%  url 'step4'  %}">
          <button class="wrap_button">Safety with a Protection Order</button>
          </a>
        </div></td>
   </tbody>  
    <tbody>
        <td><div class="span12" style="text-align:center ">
          <a href="{% url 'form_view4'  %}">
          <button class="wrap_button">View</button>
          </a>
        </div></td>
   </tbody>  
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form4 %}
          <a href="{% url 'editpost4' f.id %}">
           {% endfor %}
           <button class="wrap_button">Update</button>
          </a>  
        </div></td>
   </tbody> 
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form4 %}
          <a href="{% url 'delete-post4' f.id %}">
           {% endfor %}
           <button class="wrap_button" >Delete</button>
          </a>
        </div></td>
      </tr>
   </tbody> 


</table>


{% endblock %}

myapp/templates/form_seven_page.html
{% extends 'base.html' %}



{% block content %}

<h2>Safety and my emotional health.</h2>

<table class="table table-striped table-hover table-bordered">
       <td><div class="span12" style="text-align:center">
          <a href="{%  url 'step7'  %}">
          <button class="wrap_button">Safety and my emotional health</button>
          </a>
        </div></td>
   </tbody>  
    <tbody>
        <td><div class="span12" style="text-align:center ">
          <a href="{% url 'form_view7'  %}">
          <button class="wrap_button">View</button>
          </a>
        </div></td>
   </tbody>  
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form7 %}
          <a href="{% url 'editpost7' f.id %}">
           {% endfor %}
           <button class="wrap_button">Update</button>
          </a>
        </div></td>
   </tbody> 
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form7 %}
          <a href="{% url 'delete-post7' f.id %}">
           {% endfor %}
           <button class="wrap_button" >Delete</button>
          </a>
        </div></td>
      </tr>
   </tbody> 

</table>


{% endblock %}

myapp/templates/form_six_page.html
{% extends 'base.html' %}

<!--Row -->



{% block content %}

<h2>Safety and drug or alcohol use.</h2>

<table class="table table-striped table-hover table-bordered">
       <td><div class="span12" style="text-align:center">
          <a href="{%  url 'step6'  %}">
          <button class="button">Safety and Drug or Alcohol use</button>
          </a>
        </div></td>
   </tbody>  
    <tbody>
        <td><div class="span12" style="text-align:center ">
          <a href="{% url 'form_view6'  %}">
          <button class="wrap_button">View</button>
          </a>
        </div></td>
   </tbody>  
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form6 %}
          <a href="{% url 'editpost6' f.id %}">
           {% endfor %}
           <button class="wrap_button">Update</button>
          </a>
        </div></td>
   </tbody> 
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form6 %}
          <a href="{% url 'delete-post6' f.id %}">
           {% endfor %}
           <button class="wrap_button" >Delete</button>
          </a>
        </div></td>
      </tr>
   </tbody> 


</table>


{% endblock %}

myapp/templates/form_three_page.html
{% extends 'base.html' %}

<!--Row -->



{% block content %}

<h2>Safety in my own residence.</h2>

<table class="table table-striped table-hover table-bordered">

       <td><div class="span12" style="text-align:center">
          <a href="{%  url 'step3'  %}">
          <button class="button">Safety in my Own Residence</button>
          </a>
        </div></td>
   </tbody>  
    <tbody>
        <td><div class="span12" style="text-align:center">
          <a href="{% url 'form_view3'  %}">
          <button class="button">View</button>
          </a>
        </div></td>
   </tbody>  
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form3 %}
          <a href="{% url 'editpost3' f.id %}">
           {% endfor %}
           <button class="button">Update</button>
          </a>
        </div></td>
   </tbody> 
  <tbody>
        <td><div class="span12" style="text-align:center">
          {% for f in form3 %}
          <a href="{% url 'delete-post3' f.id %}">
           {% endfor %}
           <button class="button" >Delete</button>
          </a>
        </div></td>
      </tr>
   </tbody> 


</table>


{% endblock %}

myapp/templates/form_view3.html
{% extends 'base.html' %}
{% block content %}


<body>
   <div class="card card-body">
       {% if step3 %}
          {% for st in step3 %}

           <h3>Safety in my own residence.</h3>

              <p></p>
              There are many things that a victim of domestic violence can do to increase their safety in their own residence. It may be impossible to do everything at once, but safety measures can be added step by step.
              <p></p>

              <b>Safety measures I can use:</b>
              <p>
              <p><b>A.</b> I can change the locks on my doors and windows as soon as possible.</p>
              <p><b>B.</b> I can replace wooden doors with steel/metal doors.</p>
              <p>
              <b>C.</b> I can install security systems including additional locks, window bars, and poles to wedge against doors, an electronic system, etc.
              <p>
              <b>D.</b> I can purchase rope ladders to be used for escape from second floor windows.
              <p>
              <b>E.</b> I can install smoke detectors and fire extinguishers for each floor of my house/apartment.
              <p>
              <b>F.</b> I can install an outside lighting system that activates when a person is close to the house.
              <p>
              <b>G.</b> I will teach my children how to make a collect call to me and to <b>{{st.box1}}</b> (name of friend,
                etc.) in the event that my partner takes the children.
              <p>
              <b>H.</b> I will tell the people who take care of my children which people have permission to pick up my children and that my partner is not permitted to do so. The people I will inform about pick-up permission include:
              </p>

             <b>{{st.box2}}</b> (name of school) <p><p>
             <b>{{st.box3}}</b> (name of babysitter)<p>
             <b>{{st.box4}}</b> (name of teacher)   <p>
             <b>{{st.box5}}</b> (name of Sunday-school teacher) <p>
             <b>{{st.box6}}</b> (name[s] of others)

             <p></p>
             <p>

              <b>I.</b> I can inform <b>{{st.box7}}</b>(neighbor) and <b>{{st.box8}}</b>(friend) that my partner no longer resides with me and that they should call the police if he is observed near my residence.



           {% endfor %}
   </div>
           {% else %}
               <meta http-equiv="refresh" content="0; url=http://127.0.0.1:8000/form_view_error" />
          {% endif %}


</body>

{% endblock content %}